LIBRETRO_COMM_DIR := $(CORE_DIR)/src/libretro-common
INCFLAGS := -I$(CORE_DIR)/src -I$(LIBRETRO_COMM_DIR)/include

ifneq (,$(findstring msvc200,$(platform)))
    INCFLAGS += -I$(LIBRETRO_COMM_DIR)/include/compat/msvc
endif

SOURCES_C =

SOURCES_C += $(CORE_DIR)/src/6809disasm.c
SOURCES_C += $(CORE_DIR)/src/6809cpu.c
SOURCES_C += $(CORE_DIR)/src/autostart.c
SOURCES_C += $(CORE_DIR)/src/debugger.c
SOURCES_C += $(CORE_DIR)/src/devices.c
SOURCES_C += $(CORE_DIR)/src/libretro.c
SOURCES_C += $(CORE_DIR)/src/keymap.c
SOURCES_C += $(CORE_DIR)/src/motoemulator.c
SOURCES_C += $(CORE_DIR)/src/sap.c
SOURCES_C += $(CORE_DIR)/src/video.c
SOURCES_C += $(CORE_DIR)/src/vkeyb/ui.c
SOURCES_C += $(CORE_DIR)/src/vkeyb/vkeyb.c
SOURCES_C += $(CORE_DIR)/src/vkeyb/vkeyb_config.c
SOURCES_C += $(CORE_DIR)/src/vkeyb/vkeyb_layout.c

ifneq ($(STATIC_LINKING), 1)
    SOURCES_C += $(LIBRETRO_COMM_DIR)/compat/compat_posix_string.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/compat/compat_strcasestr.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/compat/compat_strl.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/compat/fopen_utf8.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/encodings/encoding_utf.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/file/file_path.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/file/file_path_io.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/streams/file_stream.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/time/rtime.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/utils/md5.c
    SOURCES_C += $(LIBRETRO_COMM_DIR)/vfs/vfs_implementation.c
endif
